### ISSUE TITLE
How to stream video with your example?

### ISSUE THREAD

**Issue by MeteorBurn** [SlowLogicBoy/YoutubeExplode.AspNetCore.Mvc#1]
Please describe step to step how to stream video with your example?
Where I need to specify an id of video or stream link to stream it on YouTube and how can I run it?
I'm a newbie here)
Thank you!

**Comment by SlowLogicBoy** [comment]
You can't stream with this project to or on youtube.
This is for downloading audio from youtube videos. (for videos you'll need to modify the code a bit)

If you want to download a audio with this:
1. Choose yt video (https://www.youtube.com/watch?v=Z11c2oFU_rM)
1. Run the code
1. Go to http://localhost:5000/youtube/download/{id} (http://localhost:5000/youtube/download/Z11c2oFU_rM)
1. it will start downloading file for you.

You can put that url to VLC it will also start playing.
It doesn't work with youtube streams though.

**Comment by MeteorBurn** [comment]
Thank you!
My language knowledge collision)
